name: flutter_fuchsia
description: Tools for driving test Flutter Applications on Fuchsia
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

dependencies:
  json_rpc_2: 2.0.4
  logging: 0.11.3+1
  process: 2.0.7
  usage: 3.3.0
  web_socket_channel: 1.0.6
